### ISSUE TITLE
Support AWS autoscaling groups

### ISSUE THREAD

**Issue by ruudk** [jason-riddle/shudder#1]
The [original shudder](https://github.com/scopely/shudder) can also listen to AWS Autoscaling Licecycle Hooks. 

Will that be supported too?

**Comment by ruudk** [comment]
Through your public profile I already came to https://github.com/JustScaleIt/lifecycled which is exactly what I need. Thanks anyway :)

**Comment by jason-riddle** [comment]
No problem. The code is a bit rough for both repositories so any feedback is appreciated.
